#!/usr/bin/env python3

import sys
import os
import re


loop=0
for root, dirs, files in os.walk(".", topdown=False):
	loop=loop+1

	for name in files:
		file=os.path.join(root, name)
		parts=file.split('/')

		nrofparts=len(parts)

		file_name=parts[-1]
		file_path='/'.join(parts[2:-1])

		page_name=parts[1]

		ext='.'.join(file.split('.')[2:])

		with open(file,'r') as f:
			for line in f.readlines():
				a=re.findall(r'export class (\w+) {',line)
				if a != []:
					page=a[0]

		if (ext == 'ts'):
			type='PAGE'
			# export class PageTwo {

			pass
		elif (ext == 'module.ts'):
			type='MODULE'
			# import { PageOne } from "./page-one";
			#
			# @NgModule({
			#	declarations: [PageOne],
			#	imports: [IonicPageModule.forChild(PageOne)],
			#	entryComponents: [PageOne]
			#	})
			# export class PageOneModule {}

			pass
		elif (ext == 'html'):
			type='HTML'
			page=''
		else:
			type='UNKNOWN'
			page=''
			
		print('OUT: %-6s %-40s ==> %s: %s' % (type, file, ext, page))

	if (loop > 20):
		sys.exit()
